### ISSUE TITLE
Vault Conversion

### ISSUE THREAD

**Issue by ShaneBeee** [OfficialDonut/SkVault#3]
So in Vault there is a conversion tool /vault-convert eco1 eco2

This allows someone to convert their economy from one plugin to the next.
Now I tried to convert from Essentials to my eco. And it ran a big error. Based on reading some facts on vault, i dont know if this is a problem with vault or with SkVault.
Im thinking something might be missing "HasAccountRequest" maybe I'm doing something wrong?

Here is the error it spews out when I try
```
[15:36:55 WARN]: Unexpected exception while parsing console command "vault-convert EssentialsEconomy SkEco"
org.bukkit.command.CommandException: Unhandled exception executing command 'vault-convert' in plugin Vault v1.6.6-b${env.TRAVIS_BUILD_NUMBER}
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.UnsupportedOperationException: HasAccountRequest
	at us._donut_.skvault.CustomEconomy.hasAccount(CustomEconomy.java:295) ~[?:?]
	at net.milkbowl.vault.Vault.convertCommand(Vault.java:461) ~[?:?]
	at net.milkbowl.vault.Vault.onCommand(Vault.java:412) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	... 8 more
```

**Comment by OfficialDonut** [comment]
Fixed with v1.1.5
