### ISSUE TITLE
Error on load 

### ISSUE THREAD

**Issue by HollishKid** [OfficialDonut/SkVault#4]
Hey ! I'm very excited about your ressource, this is exactly what I was looking for, it's even better actually!
So I downloaded your addon and installed it on my 1.12.2 Spigot server with Vault freshly installed (v.1.6.6) and I get the following error ; am I doing something horribly wrong here?

Thanks for your help !

`[19:11:39 INFO]: [SkVault] Enabling SkVault v1.1.5
[19:11:39 ERROR]: Error occurred while enabling SkVault v1.1.5 (Is it up to date?)
java.lang.NoSuchMethodError: ch.njol.skript.lang.SkriptEventInfo.requiredPlugins([Ljava/lang/String;)Lch/njol/skript/lang/SkriptEventInfo;
at us._donut_.skvault.events.requests.BalanceRequestEvent.<clinit>(BalanceRequestEvent.java:16) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
at us._donut_.skvault.SkVault.onEnable(SkVault.java:17) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by OfficialDonut** [comment]
What version of Skript are you using?

**Comment by HollishKid** [comment]
I'm using Skript v2.2-dev32d

**Comment by OfficialDonut** [comment]
If you update it won't error but I'll make it work on older versions

**Comment by OfficialDonut** [comment]
Fixed in v1.2 https://forums.skunity.com/resources/skvault-custom-economy-support.576/update?update=1432
