### ISSUE TITLE
Check player balance request issue 

### ISSUE THREAD

**Issue by PierreBouchet** [OfficialDonut/SkVault#7]
Hi,
I'm experiencing some troubles implementing an economy system based on skvault. 
The vault deposit and withdraw requests work perfectly but i have issues with the check player balance request.
```
on vault check player balance request:
    if balance(player) is greater than event-number:
        return true
    else:
        return false
```
The error: https://pastebin.com/atzGLvnW
I'm in the last build of Skript
Paper 1.15.2 

Thanks by advance

**Comment by adri1012018** [comment]
Same:

Me I experience it with my guis and they work fine when I delete this plugin
`
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! [Skript] Severe Error:
[19:47:11 ERROR]: #!#! Could not load shops.sk
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! Something went horribly wrong with Skript.
[19:47:11 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:47:11 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[19:47:11 ERROR]: #!#! Here is full list of them:
[19:47:11 ERROR]: #!#! SkVault v2.0 Skungee v1.0.15 TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe) SkBee v1.9.1 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.4 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[19:47:11 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[19:47:11 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[19:47:11 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[19:47:11 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[19:47:11 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:47:11 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! Stack trace:
[19:47:11 ERROR]: #!#! java.lang.UnsupportedOperationException: currency-name
[19:47:11 ERROR]: #!#!     at us.donut.skvault.EconomyProperty.getValue(EconomyProperty.java:36)
[19:47:11 ERROR]: #!#!     at us.donut.skvault.CustomEconomy.currencyNameSingular(CustomEconomy.java:77)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:157)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:56)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:1)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:420)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:459)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:364)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:640)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:827)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1568)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1498)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1525)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1525)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:80)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1110)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:486)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:636)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[19:47:11 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:601)
[19:47:11 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[19:47:11 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[19:47:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294)
[19:47:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[19:47:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[19:47:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[19:47:11 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[19:47:11 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! Version Information:
[19:47:11 ERROR]: #!#!   Skript: 2.5.3 (latest)
[19:47:11 ERROR]: #!#!     Flavor: skriptlang-github
[19:47:11 ERROR]: #!#!     Date: 2020-12-11
[19:47:11 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[19:47:11 ERROR]: #!#!   Minecraft: 1.16.4
[19:47:11 ERROR]: #!#!   Java: 1.8.0_271 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09)
[19:47:11 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! Server platform: Paper
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! Current node: if arg-1 is "ak-47": (shops.sk, line 4)
[19:47:11 ERROR]: #!#! Current item: null
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! Thread: Server thread
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! Language: english
[19:47:11 ERROR]: #!#! Link parse mode: DISABLED
[19:47:11 ERROR]: #!#!
[19:47:11 ERROR]: #!#! End of Error.
[19:47:11 ERROR]: #!#!`

**Comment by ninioteam** [comment]
Redownload skvault
